# Model architecture
model = "bmshj2018-factorized"

# Training dataset
dataset = "data/aid"

# Simulation runtime in seconds
simulation_time = 100.0

# Learning rate
learning_rate = 1e-4

# Dataloaders threads
num_workers = 1

# Bit-rate distortion parameter
lmbda = 1e-2

# Batch size
batch_size = 16

# Test batch size
test_batch_size = 64

# Auxiliary loss learning rate
aux_learning_rate = 1e-3

# Size of the patches to be cropped
patch_size = [256, 256]

# Use cuda
cuda = false

# Save model to disk
save = true

# Set random seed for reproducibility
seed = 42

# Gradient clipping max norm
clip_max_norm = 1.0

# Path to a checkpoint
checkpoint = ""

# Whether to use a pretrained model
pretrained = false