# Model architecture
model = "bmshj2018-factorized"

# Training dataset
dataset =  "D:/Arbeit/Code/LICOS/data/raw_test/"

# Simulation runtime in seconds
simulation_time = 86400.0

# Learning rate
learning_rate = 1e-4

# Dataloaders threads
num_workers = 1

# Bit-rate distortion parameter
lmbda = 1e-2

# Batch size
batch_size = 16

# Test batch size
test_batch_size = 64

# Auxiliary loss learning rate
aux_learning_rate = 1e-3

# Size of the patches to be cropped
patch_size = [256, 256]

# Use cuda
cuda = true

# Save model to disk
save = true

# Set random seed for reproducibility
seed = 42

# Gradient clipping max norm
clip_max_norm = 1.0

# Path to a checkpoint
checkpoint = ""

# Whether to use a pretrained model
pretrained = true

# Quality value for the model, 1 to 8
model_quality = 1

# Time needed for communications in seconds
time_for_comms = 18.375

# estimated time per batch in seconds
# note that this was computed for batchsize 16
# on a unibap iX10-100
time_per_batch = 13.63560

# Whether to use l0 data
use_l0_data = true

# L0 data formatting 
# raw - as 13 individual bands
# merged - 13 channel img
l0_format = "raw"

# For l0 data, image target resolution for merged mode.
l0_target_resolution_merged_m = 20.0

# Percentage of train partition over the whole dataset. Used only for l0 data.
l0_test_over_tot = 0.2

# Percentage of validation partition over train. Used only for l0 data.
l0_validation_over_train = 0.125

# Tolerance (percentage) on test/ train geographical splitting. Used only for l0 data.
# Set high to allow testing with small datasets.
l0_train_test_tolerance= 0.1

