# Model architecture
model = "bmshj2018-factorized"

# Training dataset
dataset = "/home/pablo/rawdata/my_tif_dir/"

# Simulation runtime in seconds
simulation_time = 2592000.0

# Learning rate
learning_rate = 1e-4

# Dataloaders threads
num_workers = 1

# Bit-rate distortion parameter
lmbda = 1e-2

# Batch size
batch_size = 16

# Test batch size
test_batch_size = 64

# Auxiliary loss learning rate
aux_learning_rate = 1e-3

# Size of the patches to be cropped
patch_size = [256, 256]

# Use cuda
cuda = true

# Save model to disk
save = true

# Set random seed for reproducibility
seed = 42

# Gradient clipping max norm
clip_max_norm = 1.0

# Path to a checkpoint
checkpoint = ""

# Whether to use a pretrained model
pretrained = true

# Quality value for the model, 1 to 8
model_quality = 1

# Time needed for communications in seconds
time_for_comms = 18.375

# estimated time per batch in seconds
# note that this was computed for batchsize 16
# on a unibap iX10-100
time_per_batch = 8.0

# Whether to use raw data
use_raw_data = true

# Raw data formatting
# split - as 13 individual bands
# merged - 13 channel img
raw_format = "split"

# For raw data, whether dataset is preloaded.
preloaded = true

# For raw data, image target resolution for merged mode.
raw_target_resolution_merged_m = 20.0

# Percentage of train partition over the whole dataset. Used only for raw data.
raw_test_over_tot = 0.2

# Percentage of validation partition over train. Used only for raw data.
raw_validation_over_train = 0.125

# Tolerance (percentage) on test/ train geographical splitting. Used only for raw data.
# Set high to allow testing with small datasets.
raw_train_test_tolerance= 0.1

# Save all the models over time
save_checkpoints_over_time = true

