name: licos
channels:
  - conda-forge
   - pytorch
 dependencies:
   - cudatoolkit
   - dotmap
   - ipykernel
   - ipywidgets
   - loguru
   - numpy
   - pandas
   - pykep
   - python=3.10
   - pytorch
   - rasterio 
   - scipy
   - scikit-spatial
   - skyfield
   - torchvision
   - toml
   - tqdm
   - pip
   - pip:
       - compressai
