name: licos
channels:
  - conda-forge
  - pytorch
dependencies:
  - cudatoolkit
  - ipykernel
  - ipywidgets
  - numpy
  - pandas
  - pykep
  - python=3.10
  - pytorch
  - scipy
  - torchvision
  - pip
  - pip:
      - compressai
