name: licos
channels:
  - conda-forge
  - pytorch
dependencies:
  - cudatoolkit
  - pandas
  - pykep
  - python=3.10
  - pytorch
  - torchvision
  - scipy
  - numpy
  - pip
  - pip:
      - compressai
